CREATE TABLE "Known_Hosts" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "IP" INTEGER NOT NULL,
    "Port" INTEGER NOT NULL,
    "Timestamp" INTEGER NOT NULL
);

CREATE TABLE "Inventory" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "Hash" BLOB NOT NULL,
    "Timestamp" INTEGER NOT NULL
);
